apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: nagp-assignment
  labels:
    app: nagp-api
    tier: api
data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: nagpdb
  DB_USER: nagpuser
